# Generated manually for LP Gestion Atelier EP Suite — TP Manager V2.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('intitule', models.CharField(max_length=260)),
                ('niveau', models.CharField(default='4', max_length=20)),
                ('version_ref', models.CharField(blank=True, max_length=220)),
                ('source_document', models.CharField(blank=True, max_length=260)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('locked_official', models.BooleanField(default=True)),
            ],
            options={'verbose_name': 'V2 diplôme Bac Pro', 'verbose_name_plural': 'V2 diplômes Bac Pro', 'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='CompetencePivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
            ],
            options={'verbose_name': 'V2 compétence pivot interne', 'verbose_name_plural': 'V2 compétences pivot internes', 'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='BacPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('libelle_officiel', models.CharField(max_length=320)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('locked_official', models.BooleanField(default=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='tp_manager.bacdiplome')),
            ],
            options={'verbose_name': 'V2 pôle officiel', 'verbose_name_plural': 'V2 pôles officiels', 'ordering': ['diplome__code', 'ordre', 'code'], 'unique_together': {('diplome', 'code')}},
        ),
        migrations.CreateModel(
            name='BacUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('libelle_officiel', models.CharField(max_length=320)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('locked_official', models.BooleanField(default=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='tp_manager.bacdiplome')),
            ],
            options={'verbose_name': 'V2 unité officielle', 'verbose_name_plural': 'V2 unités officielles', 'ordering': ['diplome__code', 'ordre', 'code'], 'unique_together': {('diplome', 'code')}},
        ),
        migrations.CreateModel(
            name='BacCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('libelle_officiel', models.CharField(max_length=420)),
                ('selectable_bac', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('locked_official', models.BooleanField(default=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_officielles', to='tp_manager.bacdiplome')),
            ],
            options={'verbose_name': 'V2 compétence officielle', 'verbose_name_plural': 'V2 compétences officielles', 'ordering': ['diplome__code', 'code'], 'unique_together': {('diplome', 'code')}},
        ),
        migrations.CreateModel(
            name='BacBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('libelle_officiel', models.CharField(max_length=360)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('locked_official', models.BooleanField(default=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_officiels', to='tp_manager.bacdiplome')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs', to='tp_manager.bacunite')),
            ],
            options={'verbose_name': 'V2 bloc officiel', 'verbose_name_plural': 'V2 blocs officiels', 'ordering': ['diplome__code', 'ordre', 'code'], 'unique_together': {('diplome', 'code')}},
        ),
        migrations.CreateModel(
            name='BacBlocCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_liees', to='tp_manager.bacbloc')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_lies', to='tp_manager.baccompetence')),
            ],
            options={'verbose_name': 'V2 compétence dans bloc officiel', 'verbose_name_plural': 'V2 compétences dans blocs officiels', 'ordering': ['bloc__diplome__code', 'bloc__ordre', 'ordre'], 'unique_together': {('bloc', 'competence')}},
        ),
        migrations.CreateModel(
            name='BacChampTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('libelle', models.CharField(max_length=220)),
                ('type_champ', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Texte long'), ('choice', 'Liste'), ('number', 'Nombre'), ('boolean', 'Oui / non')], default='text', max_length=30)),
                ('phase', models.CharField(choices=[('general', 'Création'), ('pedagogie', 'Pédagogie'), ('evaluation', 'Évaluation'), ('ressources', 'Ressources')], default='general', max_length=30)),
                ('obligatoire', models.BooleanField(default=False)),
                ('aide', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('actif', models.BooleanField(default=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs_tp', to='tp_manager.bacdiplome')),
            ],
            options={'verbose_name': 'V2 champ dynamique par diplôme', 'verbose_name_plural': 'V2 champs dynamiques par diplôme', 'ordering': ['diplome__code', 'phase', 'ordre', 'code'], 'unique_together': {('diplome', 'code')}},
        ),
        migrations.CreateModel(
            name='BacChampTPOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur', models.CharField(max_length=120)),
                ('libelle', models.CharField(max_length=220)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tp_manager.bacchamptp')),
            ],
            options={'verbose_name': 'V2 option champ dynamique', 'verbose_name_plural': 'V2 options champs dynamiques', 'ordering': ['champ__ordre', 'ordre'], 'unique_together': {('champ', 'valeur')}},
        ),
        migrations.CreateModel(
            name='TPV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=120, unique=True)),
                ('titre', models.CharField(max_length=260)),
                ('niveau_classe', models.CharField(blank=True, help_text='Seconde, Première, Terminale, groupe spécifique...', max_length=80)),
                ('usage_pedagogique', models.CharField(choices=[('decouverte', 'Découverte'), ('entrainement', 'Entraînement'), ('consolidation', 'Consolidation'), ('evaluation', 'Évaluation'), ('projet', 'Projet'), ('remediation', 'Remédiation')], default='entrainement', max_length=40)),
                ('duree_minutes', models.PositiveIntegerField(default=120)),
                ('resume_eleve', models.TextField(blank=True, help_text='Formulation simple, lisible par l’élève.')),
                ('objectifs_prof', models.TextField(blank=True, help_text='Objectifs pédagogiques côté professeur.')),
                ('mots_cles', models.CharField(blank=True, help_text='Recherche élève/parcours : domotique, PAC, diagnostic, réseau...', max_length=360)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('relecture', 'En relecture'), ('valide', 'Validé'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=40)),
                ('version', models.CharField(default='V1', max_length=40)),
                ('commentaire_interne', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tps_v2_crees', to='tp_manager.tpuser')),
                ('competence_pivot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tps', to='tp_manager.competencepivot')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tps_v2', to='tp_manager.bacdiplome')),
                ('source_tp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_transferees', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'V2 TP', 'verbose_name_plural': 'V2 TP', 'ordering': ['diplome__code', 'code']},
        ),
        migrations.CreateModel(
            name='TPV2ChampValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur', models.TextField(blank=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valeurs_tp', to='tp_manager.bacchamptp')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_champs', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'V2 valeur champ dynamique TP', 'verbose_name_plural': 'V2 valeurs champs dynamiques TP', 'ordering': ['champ__phase', 'champ__ordre'], 'unique_together': {('tp', 'champ')}},
        ),
        migrations.CreateModel(
            name='TPV2CompetenceOfficielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_lien', models.CharField(choices=[('mobilisee', 'Mobilisée'), ('travaillee', 'Travaillée'), ('dominante', 'Dominante'), ('evaluee', 'Évaluée')], default='travaillee', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tps_v2', to='tp_manager.baccompetence')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_officielles', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'V2 compétence officielle associée', 'verbose_name_plural': 'V2 compétences officielles associées', 'ordering': ['competence__code'], 'unique_together': {('tp', 'competence', 'type_lien')}},
        ),
        migrations.CreateModel(
            name='TPV2CritereReussite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=320)),
                ('description', models.TextField(blank=True)),
                ('niveau_attendu', models.CharField(blank=True, max_length=120)),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres_reussite', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'V2 critère de réussite TP', 'verbose_name_plural': 'V2 critères de réussite TP', 'ordering': ['ordre', 'id']},
        ),
        migrations.CreateModel(
            name='TPV2CritereEvaluationFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=320)),
                ('indicateur', models.TextField(blank=True)),
                ('bareme', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres_evaluation_finale', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'V2 critère d’évaluation finale TP', 'verbose_name_plural': 'V2 critères d’évaluation finale TP', 'ordering': ['ordre', 'id']},
        ),
        migrations.CreateModel(
            name='TPV2Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('pdf_eleve', 'PDF élève'), ('docx_prof', 'DOCX professeur'), ('corrige', 'Corrigé'), ('annexe', 'Annexe'), ('ressource', 'Ressource')], default='ressource', max_length=30)),
                ('titre', models.CharField(max_length=220)),
                ('fichier', models.FileField(upload_to='tpv2/documents/')),
                ('visible_eleve', models.BooleanField(default=True)),
                ('visible_prof', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_v2', to='tp_manager.tpv2')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_tpv2', to='tp_manager.tpuser')),
            ],
            options={'verbose_name': 'V2 document TP', 'verbose_name_plural': 'V2 documents TP', 'ordering': ['tp__code', 'titre']},
        ),
        migrations.CreateModel(
            name='TPV2ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(default='Groupe de ressources', max_length=220)),
                ('operator', models.CharField(choices=[('ALL', 'ET — toutes les ressources du groupe sont nécessaires'), ('ANY', 'OU — une ressource du groupe suffit')], default='ALL', max_length=10)),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('commentaire', models.TextField(blank=True)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_groups', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'V2 groupe ressources TP', 'verbose_name_plural': 'V2 groupes ressources TP', 'ordering': ['ordre', 'id']},
        ),
        migrations.CreateModel(
            name='TPV2ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_module', models.CharField(choices=[('system_manager', 'System Manager'), ('toolmag', 'ToolMag'), ('pedashop', 'PedaShop'), ('manual', 'Saisie manuelle')], default='manual', max_length=40)),
                ('resource_type', models.CharField(choices=[('systeme', 'Système'), ('outil', 'Outil'), ('mesure', 'Appareil de mesure'), ('materiel', 'Matériel'), ('consommable', 'Consommable'), ('logiciel', 'Logiciel'), ('autre', 'Autre')], default='autre', max_length=40)),
                ('external_id', models.CharField(blank=True, help_text='ID de l’objet dans le module source si connu.', max_length=120)),
                ('external_code', models.CharField(blank=True, max_length=120)),
                ('libelle', models.CharField(max_length=260)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unite', models.CharField(blank=True, max_length=40)),
                ('commentaire', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tp_manager.tpv2resourcegroup')),
            ],
            options={'verbose_name': 'V2 ressource TP', 'verbose_name_plural': 'V2 ressources TP', 'ordering': ['group__ordre', 'source_module', 'libelle']},
        ),
        migrations.CreateModel(
            name='TPV2TransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.CharField(choices=[('T0', 'T0 — non transférable'), ('T1', 'T1 — découverte'), ('T2', 'T2 — partiel'), ('T3', 'T3 — adapté'), ('T4', 'T4 — fort')], default='T2', max_length=2)),
                ('recommandation', models.TextField(blank=True)),
                ('limites', models.TextField(blank=True)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_rules_cible', to='tp_manager.bacdiplome')),
                ('competence_pivot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_rules', to='tp_manager.competencepivot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_rules_source', to='tp_manager.bacdiplome')),
            ],
            options={'verbose_name': 'V2 règle de transfert référentiel', 'verbose_name_plural': 'V2 règles de transfert référentiel', 'ordering': ['source__code', 'cible__code', 'niveau'], 'unique_together': {('source', 'cible', 'competence_pivot')}},
        ),
    ]
