# Generated by Django 5.0.7 on 2026-05-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_manager', '0006_tpv2_parcours_affectation_bareme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpv2',
            name='domaine_principal',
            field=models.CharField(blank=True, help_text='Thème principal utilisé dans le repère automatique : domotique, PAC, réseau, câblage...', max_length=120),
        ),
        migrations.AlterField(
            model_name='tpv2',
            name='objectifs_prof',
            field=models.TextField(blank=True, help_text='Description du contexte / mise en situation professionnelle.'),
        ),
    ]
