# Generated by Django 5.0.7 on 2026-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_users_excel_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, help_text='Laisser vide pour générer automatiquement : 3 premières lettres de la catégorie + indice. Exemple : OUT-004', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('storekeeper', 'Magasinier'), ('tech_inventory', 'Technicien inventaire'), ('responsible', 'Responsable'), ('read_only', 'Lecture seule'), ('admin', 'Administrateur')], default='user', max_length=30),
        ),
    ]
