# Generated by Django 5.0.7 on 2026-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipment_code_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forcer le changement de mot de passe à la prochaine connexion'),
        ),
        migrations.AddField(
            model_name='person',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Mot de passe ToolMag chiffré', max_length=255),
        ),
    ]
