# Generated by Django 5.0.7 on 2026-05-13 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_componentcheck_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('block', models.CharField(blank=True, max_length=160)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='inventory.formation')),
            ],
            options={
                'verbose_name': 'Compétence référentiel',
                'verbose_name_plural': 'Compétences référentiel',
                'ordering': ['formation__code', 'code'],
                'unique_together': {('formation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PedagogicalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('class_name', models.CharField(blank=True, max_length=80)),
                ('group_name', models.CharField(blank=True, max_length=80)),
                ('school_year', models.CharField(blank=True, max_length=20)),
                ('objectives', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='inventory.formation')),
                ('targeted_competences', models.ManyToManyField(blank=True, related_name='targeted_sessions', to='inventory.competence')),
            ],
            options={
                'verbose_name': 'Séance pédagogique',
                'verbose_name_plural': 'Séances pédagogiques',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('checkout', 'Sortie matériel'), ('return', 'Retour matériel'), ('inventory_out', 'Inventaire sortie kit'), ('inventory_return', 'Inventaire retour kit'), ('equipment_create', 'Création fiche matériel'), ('equipment_update', 'Modification fiche matériel'), ('user_management', 'Gestion utilisateurs'), ('promotion', 'Montée pédagogique')], max_length=40)),
                ('role', models.CharField(blank=True, choices=[('user', 'Utilisateur'), ('storekeeper', 'Magasinier'), ('tech_inventory', 'Technicien inventaire'), ('responsible', 'Responsable'), ('read_only', 'Lecture seule'), ('admin', 'Administrateur')], max_length=30)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('criterion', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='inventory.competence')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_mappings', to='inventory.formation')),
            ],
            options={
                'verbose_name': 'Correspondance action-compétence',
                'verbose_name_plural': 'Correspondances actions-compétences',
                'ordering': ['formation__code', 'action_type', 'role', 'competence__code'],
                'unique_together': {('formation', 'action_type', 'role', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('user', 'Utilisateur'), ('storekeeper', 'Magasinier'), ('tech_inventory', 'Technicien inventaire'), ('responsible', 'Responsable'), ('read_only', 'Lecture seule'), ('admin', 'Administrateur')], max_length=30)),
                ('proposed_level', models.PositiveSmallIntegerField(default=0)),
                ('validated_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('auto', 'Proposition automatique'), ('teacher', 'Validation professeur')], default='auto', max_length=20)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inventory.competence')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inventory.person')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_evaluations', to='inventory.person')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inventory.pedagogicalsession')),
            ],
            options={
                'verbose_name': 'Évaluation compétence',
                'verbose_name_plural': 'Évaluations compétences',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'person', 'competence', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SessionRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('storekeeper', 'Magasinier'), ('tech_inventory', 'Technicien inventaire'), ('responsible', 'Responsable'), ('read_only', 'Lecture seule'), ('admin', 'Administrateur')], default='user', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assignments', to='inventory.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.pedagogicalsession')),
            ],
            options={
                'verbose_name': 'Affectation de rôle séance',
                'verbose_name_plural': 'Affectations de rôles séance',
                'ordering': ['session', 'person__last_name', 'person__first_name'],
                'unique_together': {('session', 'person', 'role')},
            },
        ),
    ]
