# Generated by Django 5.0.7 on 2026-05-14 01:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_competence_pedagogicalsession_competencemapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_enabled', models.BooleanField(default=False, verbose_name='Module armoires sécurisées actif')),
                ('require_authorized_terminal', models.BooleanField(default=True, verbose_name='Exiger un terminal autorisé')),
                ('require_allowed_public_ip', models.BooleanField(default=True, verbose_name='Exiger une IP publique autorisée')),
                ('allowed_public_ips', models.TextField(blank=True, help_text='IP publiques autorisées, une par ligne ou séparées par des virgules. Exemple : 82.120.45.18')),
                ('allow_superadmin_force_without_terminal', models.BooleanField(default=False, verbose_name='Autoriser le forçage super admin sans terminal autorisé')),
                ('allow_superadmin_force_without_ip', models.BooleanField(default=False, verbose_name='Autoriser le forçage super admin hors IP autorisée')),
                ('script_timeout_seconds', models.PositiveSmallIntegerField(default=5, help_text='Temps maximum d’attente du script d’ouverture casier', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Paramètres armoires sécurisées',
                'verbose_name_plural': 'Paramètres armoires sécurisées',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='secure_cabinet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro d’armoire'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='secure_locker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de casier'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='secure_storage',
            field=models.BooleanField(default=False, verbose_name='Stocké en armoire sécurisée'),
        ),
        migrations.CreateModel(
            name='AuthorizedTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('terminal_type', models.CharField(choices=[('tablet', 'Tablette'), ('pc', 'PC'), ('display', 'Affichage dynamique'), ('other', 'Autre')], default='tablet', max_length=20)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('can_open_lockers', models.BooleanField(default=False, verbose_name='Autorisé à ouvrir les casiers')),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals_created', to='inventory.person')),
            ],
            options={
                'verbose_name': 'Terminal autorisé',
                'verbose_name_plural': 'Terminaux autorisés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LockerOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinet', models.CharField(max_length=50)),
                ('locker', models.CharField(max_length=50)),
                ('context', models.CharField(choices=[('checkout', 'Sortie'), ('return', 'Retour'), ('maintenance', 'Maintenance / contrôle'), ('force', 'Forçage super admin'), ('detail', 'Fiche matériel')], default='detail', max_length=30)),
                ('success', models.BooleanField(default=False)),
                ('refused', models.BooleanField(default=False)),
                ('refusal_reason', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('controller_response', models.TextField(blank=True)),
                ('client_ip', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_logs', to='inventory.equipment')),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_open_logs', to='inventory.person')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_open_logs', to='inventory.authorizedterminal')),
            ],
            options={
                'verbose_name': 'Journal ouverture casier',
                'verbose_name_plural': 'Journal ouvertures casiers',
                'ordering': ['-created_at'],
            },
        ),
    ]
