# Generated by ToolMag V18
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_repairlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_type', models.CharField(choices=[('out', 'Contrôle utilisateur avant sortie'), ('return', 'Contrôle utilisateur avant retour')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis au magasinier'), ('applied', 'Validé par le magasinier'), ('cancelled', 'Annulé')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('global_condition', models.CharField(choices=[('new', 'Neuf'), ('good', 'Bon état'), ('normal_wear', 'Usure normale'), ('watch', 'À surveiller'), ('damaged', 'Abîmé'), ('incomplete', 'Incomplet'), ('dangerous', 'Dangereux')], default='good', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_user_inventories', to='inventory.person')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_inventories', to='inventory.person')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_inventories', to='inventory.equipment')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inventories', to='inventory.loan')),
            ],
            options={
                'verbose_name': 'Inventaire utilisateur',
                'verbose_name_plural': 'Inventaires utilisateurs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('good', 'Bon état'), ('normal_wear', 'Usure normale'), ('watch', 'À surveiller'), ('damaged', 'Abîmé'), ('incomplete', 'Incomplet'), ('dangerous', 'Dangereux')], default='good', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.component')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.userinventory')),
            ],
            options={
                'verbose_name': 'Ligne inventaire utilisateur',
                'verbose_name_plural': 'Lignes inventaires utilisateurs',
                'ordering': ['component__sort_order', 'component__name'],
                'unique_together': {('inventory', 'component')},
            },
        ),
    ]
