# Generated by ToolMag V20
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_userinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(choices=[('notice', 'Notice constructeur'), ('quickstart', 'Fiche de prise en main'), ('safety', 'Consignes de sécurité'), ('maintenance', 'Fiche maintenance'), ('other', 'Autre document')], default='notice', max_length=30)),
                ('file', models.FileField(upload_to='equipment_documents/')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'Document matériel',
                'verbose_name_plural': 'Documents matériels',
                'ordering': ['sort_order', 'document_type', 'title'],
            },
        ),
    ]
