# Generated by Django 5.0.7 on 2026-05-18 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_equipment_description_interventionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencemapping',
            name='action_type',
            field=models.CharField(choices=[('checkout', 'Sortie matériel'), ('return', 'Retour matériel'), ('inventory_out', 'Inventaire sortie kit'), ('inventory_return', 'Inventaire retour kit'), ('user_inventory_out', 'Inventaire utilisateur sortie'), ('user_inventory_return', 'Inventaire utilisateur retour'), ('equipment_create', 'Création fiche matériel'), ('equipment_update', 'Modification fiche matériel'), ('user_management', 'Gestion utilisateurs'), ('promotion', 'Montée pédagogique')], max_length=40),
        ),
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='MaterialEditGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(blank=True, max_length=80)),
                ('group_name', models.CharField(blank=True, max_length=80)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('can_create_equipment', models.BooleanField(default=False, verbose_name='Créer matériel')),
                ('can_edit_equipment', models.BooleanField(default=False, verbose_name='Modifier fiche matériel')),
                ('can_add_photo', models.BooleanField(default=False, verbose_name='Ajouter / modifier photo')),
                ('can_add_document', models.BooleanField(default=False, verbose_name='Ajouter document')),
                ('can_edit_components', models.BooleanField(default=False, verbose_name='Modifier composants')),
                ('can_edit_location', models.BooleanField(default=False, verbose_name='Modifier emplacement')),
                ('can_edit_description', models.BooleanField(default=False, verbose_name='Modifier descriptif')),
                ('can_generate_qr', models.BooleanField(default=False, verbose_name='Générer QR')),
                ('comment', models.TextField(blank=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_edit_grants', to='inventory.formation')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_grants_given', to='inventory.person')),
            ],
            options={
                'verbose_name': 'Droit ponctuel matériel',
                'verbose_name_plural': 'Droits ponctuels matériel',
                'ordering': ['-start_date', 'formation__code', 'class_name', 'group_name'],
            },
        ),
    ]
