# Generated by Django 5.0.7 on 2026-05-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_competencemapping_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Composant', 'verbose_name_plural': 'Composants'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['code'], 'verbose_name': 'Matériel', 'verbose_name_plural': 'Matériels'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['code'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-checked_out_at'], 'verbose_name': 'Sortie / emprunt', 'verbose_name_plural': 'Sorties / emprunts'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Emplacement', 'verbose_name_plural': 'Emplacements'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Personne', 'verbose_name_plural': 'Personnes'},
        ),
        migrations.AlterField(
            model_name='authorizedterminal',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='competencemapping',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='new_class_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='new_group_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='old_class_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='old_group_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, help_text='Laisser vide pour générer automatiquement : 3 premières lettres de la catégorie + indice. Exemple : OUT-004', max_length=32, unique=True, verbose_name='Code matériel'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_condition',
            field=models.CharField(choices=[('new', 'Neuf'), ('good', 'Bon état'), ('normal_wear', 'Usure normale'), ('watch', 'À surveiller'), ('damaged', 'Abîmé'), ('incomplete', 'Incomplet'), ('dangerous', 'Dangereux'), ('absent', 'Absent')], default='good', max_length=30, verbose_name='État actuel'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='display_on_public_screen',
            field=models.BooleanField(default=True, verbose_name='Afficher sur écran dynamique'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('simple', 'Matériel simple'), ('kit', 'Matériel composé / kit'), ('consumable', 'Consommable')], default='simple', max_length=20, verbose_name='Type de matériel'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_required_out',
            field=models.BooleanField(default=False, verbose_name='Inventaire requis à la sortie'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_required_return',
            field=models.BooleanField(default=False, verbose_name='Inventaire requis au retour'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Emplacement'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='equipment/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sensitive',
            field=models.BooleanField(default=False, verbose_name='Matériel sensible'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Numéro de série'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('out', 'Sorti'), ('late', 'En retard'), ('maintenance', 'Maintenance'), ('incomplete', 'Incomplet'), ('out_of_service', 'Hors service'), ('lost', 'Perdu')], default='available', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='equipmentdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='referential_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nom du référentiel'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='materialeditgrant',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='materialeditgrant',
            name='class_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='materialeditgrant',
            name='group_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='pedagogicalsession',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='pedagogicalsession',
            name='class_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='pedagogicalsession',
            name='group_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='person',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AlterField(
            model_name='person',
            name='class_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, max_length=120, verbose_name='Service / département'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='inventory.formation', verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(blank=True, max_length=80, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=120, verbose_name='UID RFID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('storekeeper', 'Magasinier'), ('tech_inventory', 'Technicien inventaire'), ('responsible', 'Responsable'), ('read_only', 'Lecture seule'), ('admin', 'Administrateur')], default='user', max_length=30, verbose_name='Rôle principal'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Identifiant'),
        ),
    ]
