# Generated by Django 5.0.7 on 2026-05-18 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_category_options_alter_component_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Classe')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_classes', to='inventory.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Classe pédagogique',
                'verbose_name_plural': 'Classes pédagogiques',
                'ordering': ['formation__code', 'name'],
                'unique_together': {('formation', 'name')},
            },
        ),
    ]
