# Generated by Django 5.0.7 on 2026-05-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('to_verify', 'À vérifier'), ('out', 'Sorti'), ('late', 'En retard'), ('maintenance', 'Maintenance'), ('incomplete', 'Incomplet'), ('out_of_service', 'Hors service'), ('lost', 'Perdu')], default='available', max_length=30, verbose_name='Statut'),
        ),
    ]
