# Generated by patch_toolmag_compartiments_zones.py
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('armoire', 'Armoire'), ('etagere', 'Étagère'), ('tableau', 'Tableau'), ('rayonnage', 'Rayonnage'), ('zone', 'Zone atelier'), ('autre', 'Autre')], default='armoire', max_length=30, verbose_name='Type d’emplacement'),
        ),
        migrations.AddField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, help_text='Exemple : A1, E2, TGBT1', max_length=50, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.CharField(blank=True, help_text='Exemple : étagère 2, tablette haute, rangée B', max_length=80, verbose_name='Niveau / tablette / tiroir'),
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.CharField(blank=True, help_text='Exemple : place 04, bac 12, crochet 08', max_length=80, verbose_name='Place / crochet / bac'),
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, max_length=120, verbose_name='Salle / local'),
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Zone interne'),
        ),
        migrations.AddField(
            model_name='location',
            name='secure_storage',
            field=models.BooleanField(default=False, verbose_name='Emplacement sécurisé'),
        ),
        migrations.AddField(
            model_name='location',
            name='secure_cabinet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro d’armoire sécurisée'),
        ),
        migrations.AddField(
            model_name='location',
            name='secure_locker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de casier'),
        ),

        migrations.AddField(
            model_name='component',
            name='line_type',
            field=models.CharField(choices=[('component', 'Composant réel'), ('section', 'Section / compartiment'), ('note', 'Note libre')], default='component', help_text='Composant réel, section/tiroir/poche, ou note libre.', max_length=20, verbose_name='Type de ligne'),
        ),
        migrations.AddField(
            model_name='component',
            name='section_label',
            field=models.CharField(blank=True, help_text='Optionnel : précision de section ou note.', max_length=160, verbose_name='Libellé complémentaire'),
        ),
        migrations.AddField(
            model_name='component',
            name='mobile_page_break',
            field=models.BooleanField(default=True, help_text='Pour une section : démarre une nouvelle page dans l’inventaire téléphone.', verbose_name='Nouvelle page mobile'),
        ),
        migrations.AddField(
            model_name='component',
            name='inventory_required',
            field=models.BooleanField(default=True, help_text='Désactiver pour une note ou une ligne informative.', verbose_name='À contrôler en inventaire'),
        ),

        migrations.AddField(
            model_name='loan',
            name='destination_zone_core_id',
            field=models.CharField(blank=True, help_text='Identifiant de la zone atelier issue de LP Core.', max_length=80, verbose_name='ID zone LP Core'),
        ),
        migrations.AddField(
            model_name='loan',
            name='destination_zone_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Code zone LP Core'),
        ),
        migrations.AddField(
            model_name='loan',
            name='destination_zone_label_snapshot',
            field=models.CharField(blank=True, help_text='Libellé copié au moment de la sortie pour conserver l’historique.', max_length=180, verbose_name='Destination atelier'),
        ),
        migrations.AddField(
            model_name='loan',
            name='destination_zone_free_text',
            field=models.CharField(blank=True, help_text='À utiliser si la zone LP Core n’est pas encore disponible.', max_length=180, verbose_name='Destination libre'),
        ),
    ]
