# Generated by Django 5.0.7 on 2026-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rgpd_profiles_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Oblige l’utilisateur à changer son mot de passe à la prochaine connexion LP Core.'),
        ),
        migrations.AlterField(
            model_name='suitemaintenancejob',
            name='action',
            field=models.CharField(choices=[('apply_public_settings', 'Appliquer URLs / HTTPS'), ('issue_cert', 'Générer certificat'), ('renew_cert', 'Renouveler certificat'), ('cert_status', 'État certificat'), ('restart_services', 'Redémarrer services'), ('migrate_all', 'Lancer migrations'), ('backup_all', 'Sauvegarde historique'), ('full_backup', 'Sauvegarde complète de reprise'), ('restore_full_backup', 'Restauration complète après crash'), ('install_update', 'Installer mise à jour ZIP')], max_length=80),
        ),
    ]
