# Generated by assistant for LP Gestion Atelier Suite Bêta V0.0.1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_module_access_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgpdpolicysettings',
            name='technical_logs_retention',
            field=models.CharField(default='90 jours', max_length=120),
        ),
        migrations.AlterField(
            model_name='rgpdpolicysettings',
            name='backup_retention_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='rgpdpolicysettings',
            name='certification_support_note',
            field=models.TextField(default='Les sauvegardes automatiques sont conservées par défaut 7 jours glissants. Les sauvegardes manuelles et pré-mise-à-jour sont conservées sans suppression automatique, sauf action volontaire d’un administrateur.'),
        ),
        migrations.CreateModel(
            name='BackupPolicySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automatic_enabled', models.BooleanField(default=True)),
                ('daily_hour', models.PositiveSmallIntegerField(default=2)),
                ('daily_minute', models.PositiveSmallIntegerField(default=0)),
                ('daily_retention_days', models.PositiveIntegerField(default=7)),
                ('manual_keep_forever', models.BooleanField(default=True)),
                ('pre_upgrade_required', models.BooleanField(default=True)),
                ('block_update_if_backup_failed', models.BooleanField(default=True)),
                ('web_restore_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='Sauvegarde quotidienne automatique, conservation glissante configurable. Sauvegardes manuelles et pré-mise-à-jour conservées sans suppression automatique.')),
            ],
            options={
                'verbose_name': 'Paramètres sauvegarde',
                'verbose_name_plural': 'Paramètres sauvegarde',
            },
        ),
    ]
