blank_issues_enabled: true
contact_links:
  - name: Documentation du projet
    url: https://github.com/nvivionprof/lp-gestion-atelier-ep-suite
    about: Consulter le README et la documentation du dépôt.
