from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = Path(os.getenv('LP_CORE_DATA_DIR', BASE_DIR / 'data'))
DATA_DIR.mkdir(parents=True, exist_ok=True)

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-only-change-me-lp-core')
DEBUG = os.getenv('DJANGO_DEBUG', '1') == '1'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')
CSRF_TRUSTED_ORIGINS = [origin for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'lp_core_tls_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lp_core_project.urls'
TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
        'core.context_processors.core_context',
    ]},
}]
WSGI_APPLICATION = 'lp_core_project.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', str(DATA_DIR / 'lp-core.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
}

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True
STATIC_URL = '/static/'
STATIC_ROOT = Path(os.getenv('STATIC_ROOT', DATA_DIR / 'staticfiles'))
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', DATA_DIR / 'media'))
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LP_CORE_API_TOKEN = os.getenv('LP_CORE_API_TOKEN', 'dev-token-change-me')
LP_CORE_PUBLIC_NAME = os.getenv('LP_CORE_PUBLIC_NAME', 'LP Gestion Atelier EP Suite')
LP_CORE_VERSION = os.getenv('LP_CORE_VERSION', 'LP Core — RC V0.0.1')
LP_CORE_EXPOSE_INITIAL_PASSWORD_FOR_SYNC = os.getenv('LP_CORE_EXPOSE_INITIAL_PASSWORD_FOR_SYNC', '1') == '1'
MODULE_SYNC_TIMEOUT_SECONDS = int(os.getenv('MODULE_SYNC_TIMEOUT_SECONDS', '90'))


# Public URLs and ports generated by install.sh
SERVER_IP = os.getenv('SERVER_IP', 'localhost')
LP_CORE_PORT = os.getenv('LP_CORE_PORT', '9000')
TOOLMAG_PORT = os.getenv('TOOLMAG_PORT', '9001')
SAFETY_PORT = os.getenv('SAFETY_PORT', '9002')
CONSUMABLES_PORT = os.getenv('CONSUMABLES_PORT', '9003')
INVENTORY_PORT = os.getenv('INVENTORY_PORT', '9004')
SYSTEM_MANAGER_PORT = os.getenv('SYSTEM_MANAGER_PORT', os.getenv('INVENTORY_PORT', '9004'))
TPMANAGER_PORT = os.getenv('TPMANAGER_PORT', '9005')
LP_CORE_PUBLIC_URL = os.getenv('LP_CORE_PUBLIC_URL', f'http://{SERVER_IP}:{LP_CORE_PORT}').rstrip('/')
TOOLMAG_PUBLIC_BASE_URL = os.getenv('TOOLMAG_PUBLIC_BASE_URL', f'http://{SERVER_IP}:{TOOLMAG_PORT}').rstrip('/')
SAFETY_PUBLIC_URL = os.getenv('SAFETY_PUBLIC_URL', f'http://{SERVER_IP}:{SAFETY_PORT}').rstrip('/')
CONSUMABLES_PUBLIC_URL = os.getenv('CONSUMABLES_PUBLIC_URL', f'http://{SERVER_IP}:{CONSUMABLES_PORT}').rstrip('/')
INVENTORY_PUBLIC_URL = os.getenv('INVENTORY_PUBLIC_URL', f'http://{SERVER_IP}:{INVENTORY_PORT}').rstrip('/')
SYSTEM_MANAGER_PUBLIC_URL = os.getenv('SYSTEM_MANAGER_PUBLIC_URL', INVENTORY_PUBLIC_URL).rstrip('/')
TPMANAGER_PUBLIC_URL = os.getenv('TPMANAGER_PUBLIC_URL', f'http://{SERVER_IP}:{TPMANAGER_PORT}').rstrip('/')
PFMP_PUBLIC_URL = os.getenv('PFMP_PUBLIC_URL', f'{LP_CORE_PUBLIC_URL}/pfmp').rstrip('/')

# Static files served by WhiteNoise behind Gunicorn
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

TOOLMAG_INTERNAL_SYNC_URL = os.getenv('TOOLMAG_INTERNAL_SYNC_URL', 'http://toolmag-app:8000/api/internal/sync-lp-core/')
PEDASHOP_INTERNAL_SYNC_URL = os.getenv('PEDASHOP_INTERNAL_SYNC_URL', 'http://pedashop-app:8000/api/internal/sync-lp-core/')
SAFETY_INTERNAL_SYNC_URL = os.getenv('SAFETY_INTERNAL_SYNC_URL', 'http://safety-app:8000/sync-lp-core/')
SYSTEM_MANAGER_INTERNAL_SYNC_URL = os.getenv('SYSTEM_MANAGER_INTERNAL_SYNC_URL', 'http://system-manager-app:8000/sync-lp-core/')
TPMANAGER_INTERNAL_SYNC_URL = os.getenv('TPMANAGER_INTERNAL_SYNC_URL', 'http://tpmanager-app:8000/sync-lp-core/')
PFMP_INTERNAL_SYNC_URL = os.getenv('PFMP_INTERNAL_SYNC_URL', 'http://pfmp-app:8000/sync-lp-core/')



# Reverse proxy path-prefix support for lp-gateway.
APP_URL_PREFIX = os.getenv('APP_URL_PREFIX', '').strip().rstrip('/')
if APP_URL_PREFIX:
    FORCE_SCRIPT_NAME = APP_URL_PREFIX
    STATIC_URL = f'{APP_URL_PREFIX}/static/'
    MEDIA_URL = f'{APP_URL_PREFIX}/media/'
    SESSION_COOKIE_PATH = APP_URL_PREFIX + '/'
    CSRF_COOKIE_PATH = APP_URL_PREFIX + '/'
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', '0') == '1'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', '0') == '1'

# HTTPS direct support. When Gunicorn serves TLS directly, cookies should be secure.
ENABLE_HTTPS = os.getenv('ENABLE_HTTPS', '0') == '1'
if ENABLE_HTTPS:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Cookies isolés par application : évite les collisions entre LP Core et les modules servis sur le même domaine.
SESSION_COOKIE_NAME = os.getenv('LP_CORE_SESSION_COOKIE_NAME', 'lp_core_sessionid')
CSRF_COOKIE_NAME = os.getenv('LP_CORE_CSRF_COOKIE_NAME', 'lp_core_csrftoken')
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_SAVE_EVERY_REQUEST = os.getenv('SESSION_SAVE_EVERY_REQUEST', '0') == '1'

# Maintenance web / agent interne sécurisé
LP_CORE_UPDATES_DIR = os.getenv('LP_CORE_UPDATES_DIR', str(DATA_DIR / 'updates'))
SUITE_ADMIN_AGENT_URL = os.getenv('SUITE_ADMIN_AGENT_URL', 'http://suite-admin-agent:8079')
SUITE_ALLOW_WEB_MAINTENANCE = os.getenv('SUITE_ALLOW_WEB_MAINTENANCE', '1') == '1'
MAX_UPDATE_ZIP_SIZE_MB = int(os.getenv('MAX_UPDATE_ZIP_SIZE_MB', '500'))
