# Generated for LP Gestion Atelier EP Suite V1.7 PedaShop.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('pedashop', '0001_initial')]
    operations = [
        migrations.AddField('Article', 'photo', models.ImageField(blank=True, null=True, upload_to='pedashop/articles/')),
        migrations.AddField('Article', 'fournisseur', models.CharField(blank=True, max_length=160)),
        migrations.AddField('Article', 'marche', models.CharField(blank=True, help_text='Numéro de marché, contrat ou lot fournisseur.', max_length=160)),
        migrations.AddField('StockArticleMagasin', 'stock_reserve_demande', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('StockArticleMagasin', 'stock_reserve_projection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('StockArticleMagasin', 'qte_ok', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('StockArticleMagasin', 'qte_use', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('StockArticleMagasin', 'stock_hs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('Bon', 'professeur_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_professeur', to='pedashop.pedashopuser')),
        migrations.AddField('Bon', 'nom_tp', models.CharField(blank=True, max_length=180)),
        migrations.AddField('Bon', 'classe_ou_groupe', models.CharField(blank=True, max_length=120)),
        migrations.AddField('Bon', 'date_preparation_debut', models.DateTimeField(blank=True, null=True)),
        migrations.AddField('Bon', 'date_preparation_fin', models.DateTimeField(blank=True, null=True)),
        migrations.AddField('Bon', 'date_enlevement', models.DateTimeField(blank=True, null=True)),
        migrations.AddField('Bon', 'date_cloture', models.DateTimeField(blank=True, null=True)),
        migrations.CreateModel(
            name='ProjectionPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True)),
                ('nom_tp', models.CharField(max_length=180)),
                ('classe_ou_groupe', models.CharField(blank=True, max_length=120)),
                ('formation', models.CharField(blank=True, max_length=80)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('en_cours_utilisation', 'En cours'), ('partiellement_consommee', 'Partiellement consommée'), ('consommee', 'Consommée'), ('expiree', 'Expirée'), ('annulee', 'Annulée'), ('cloturee', 'Clôturée')], default='validee', max_length=40)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections_creees', to='pedashop.pedashopuser')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projections', to='pedashop.magasin')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections_prof', to='pedashop.pedashopuser')),
            ],
            options={'ordering': ['-date_debut', 'code']},
        ),
        migrations.CreateModel(
            name='LigneProjectionPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_reservee', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('quantite_affectee_aux_demandes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_retour_prevue_defaut', models.DateField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_projection', to='pedashop.article')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedashop.emplacement')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pedashop.projectionpedagogique')),
            ],
        ),
        migrations.AddField('LigneBon', 'type_sortie', models.CharField(choices=[('definitive', 'Définitive'), ('temporaire', 'Temporaire avec retour')], default='definitive', max_length=20)),
        migrations.AddField('LigneBon', 'date_retour_prevue', models.DateField(blank=True, null=True)),
        migrations.AddField('LigneBon', 'quantite_retour_prevue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('LigneBon', 'statut_ligne', models.CharField(default='en_demande', max_length=40)),
        migrations.AddField('LigneBon', 'est_preparee', models.BooleanField(default=False)),
        migrations.AddField('LigneBon', 'date_preparation', models.DateTimeField(blank=True, null=True)),
        migrations.AddField('LigneBon', 'quantite_prelevee_sur_projection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField('LigneBon', 'preparee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_preparees', to='pedashop.pedashopuser')),
        migrations.AddField('LigneBon', 'substitution_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_substitution', to='pedashop.article')),
        migrations.AddField('LigneBon', 'projection_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bon_liees', to='pedashop.projectionpedagogique')),
        migrations.AddField('LigneBon', 'ligne_projection_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bon_liees', to='pedashop.ligneprojectionpedagogique')),
        migrations.CreateModel(
            name='RetourAttendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_attendue', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('quantite_retournee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('attendu', 'Attendu'), ('partiel', 'Partiel'), ('retourne', 'Retourné'), ('retard', 'En retard'), ('perdu', 'Perdu')], default='attendu', max_length=20)),
                ('commentaire_retour', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_attendus', to='pedashop.article')),
                ('ligne_bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours_attendus', to='pedashop.lignebon')),
                ('magasin_retour_prevu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_attendus', to='pedashop.magasin')),
            ],
            options={'ordering': ['date_retour_prevue']},
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True)),
                ('type_reclamation', models.CharField(choices=[('mauvaise_reference', 'Mauvaise référence'), ('quantite_incorrecte', 'Quantité incorrecte'), ('materiel_casse', 'Matériel cassé'), ('materiel_use', 'Matériel usé'), ('materiel_manquant', 'Matériel manquant'), ('substitution_refusee', 'Substitution refusée'), ('autre', 'Autre')], max_length=40)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('corrigee', 'Corrigée'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20)),
                ('traitement', models.TextField(blank=True)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pedashop/reclamations/')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='pedashop.bon')),
                ('concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_concerne', to='pedashop.pedashopuser')),
                ('declaree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_declarees', to='pedashop.pedashopuser')),
                ('ligne_bon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='pedashop.lignebon')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to='pedashop.pedashopuser')),
            ],
        ),
        migrations.CreateModel(
            name='BonHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('ancien_statut', models.CharField(blank=True, max_length=40)),
                ('nouveau_statut', models.CharField(blank=True, max_length=40)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='pedashop.bon')),
                ('ligne_bon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='pedashop.lignebon')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedashop.pedashopuser')),
            ],
            options={'ordering': ['-date_action']},
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_alerte', models.CharField(choices=[('OK', 'OK'), ('SOUS_STOCK_MINI', 'Sous stock mini'), ('ZERO_PAR_RESERVATION', 'Zéro par réservation'), ('RUPTURE_TEMPORAIRE_RETOUR_PREVU', 'Rupture temporaire, retour prévu'), ('RUPTURE_REELLE', 'Rupture réelle'), ('STOCK_NEGATIF_AVEC_RESERVATION', 'Stock négatif avec réservation')], default='OK', max_length=50)),
                ('type_alerte', models.CharField(blank=True, max_length=80)),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_reserve', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_preparation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_exterieur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_mini', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('message', models.TextField(blank=True)),
                ('traitee', models.BooleanField(default=False)),
                ('consultation_generee', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='pedashop.article')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='pedashop.magasin')),
            ],
            options={'ordering': ['statut_alerte', 'article__reference_interne'], 'unique_together': {('article', 'magasin')}},
        ),
        migrations.CreateModel(
            name='SupplierConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='brouillon', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='pedashop/consultations/')),
                ('date_generation_pdf', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedashop.pedashopuser')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedashop.magasin')),
            ],
            options={'ordering': ['-date_creation']},
        ),
        migrations.CreateModel(
            name='SupplierConsultationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('fabricant', models.CharField(blank=True, max_length=120)),
                ('reference_constructeur', models.CharField(blank=True, max_length=120)),
                ('quantite_souhaitee', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('equivalence_possible', models.BooleanField(default=False)),
                ('valeur_substituable_article', models.BooleanField(default=False)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedashop.article')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pedashop.supplierconsultation')),
            ],
        ),
    ]
