# Generated by Django 5.0.7 on 2026-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedashop', '0004_pedashop_v20_access_stock_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='sortie_temporaire',
            field=models.BooleanField(default=False, help_text='Ancien champ global conservé ; la V1.7 gère surtout le type de sortie par ligne.'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_demande', 'En demande'), ('en_preparation', 'En préparation'), ('en_cours_traitement', 'En cours de traitement'), ('demande_prete', 'Demande prête'), ('commande_prete', 'Commande prête'), ('en_attente_enlevement', 'En attente d’enlèvement'), ('enlevee', 'Enlevée'), ('distribuee', 'Distribuée'), ('reception_validee', 'Réception validée'), ('retour_attendu', 'Retour attendu'), ('retour_partiel', 'Retour partiel'), ('retour_complet', 'Retour complet'), ('reclamation_ouverte', 'Réclamation ouverte'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='en_demande', max_length=40),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(default='a_commander', max_length=40),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree_initiale', 'Entrée initiale'), ('reception_fournisseur', 'Réception fournisseur'), ('retour_produit', 'Retour produit'), ('sortie_definitive', 'Sortie définitive'), ('sortie_temporaire', 'Sortie temporaire'), ('retour_temporaire', 'Retour temporaire'), ('correction_inventaire', 'Correction inventaire'), ('casse', 'Casse'), ('perte', 'Perte'), ('mise_au_rebut', 'Mise au rebut'), ('transfert_interne', 'Transfert interne'), ('substitution', 'Substitution'), ('reservation_projection', 'Réservation projection'), ('consultation_fournisseur', 'Consultation fournisseur')], max_length=40),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(default='validee', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockarticlemagasin',
            name='stock_reserve',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ancien champ conservé pour compatibilité.', max_digits=12),
        ),
    ]
