from django.urls import path
from . import views

urlpatterns = [
    path('portal-login/', views.portal_login, name='pedashop_portal_login'),
    path('aide/', views.help_view, name='pedashop_help'),
    path('a-propos/', views.about_view, name='pedashop_about'),
    path('', views.dashboard, name='pedashop_dashboard'),
    path('affichage/', views.affichage_dynamique, name='pedashop_affichage'),
    path('login/', views.login_view, name='pedashop_login'),
    path('logout/', views.logout_view, name='pedashop_logout'),
    path('api/health/', views.health, name='pedashop_health'),
    path('api/internal/sync-lp-core/', views.internal_sync_lp_core, name='pedashop_internal_sync_lp_core'),
    path('api/articles/search/', views.api_article_search, name='pedashop_api_article_search'),
    path('api/magasins/search/', views.api_magasin_search, name='pedashop_api_magasin_search'),
    path('api/emplacements/search/', views.api_emplacement_search, name='pedashop_api_emplacement_search'),
    path('sync-lp-core/', views.sync_users_view, name='pedashop_sync_users'),

    path('articles/', views.article_list, name='pedashop_article_list'),
    path('articles/nouveau/', views.article_form, name='pedashop_article_create'),
    path('articles/<int:pk>/', views.article_detail, name='pedashop_article_detail'),
    path('articles/<int:pk>/modifier/', views.article_form, name='pedashop_article_edit'),
    path('articles/modele.xlsx', views.articles_template_xlsx, name='pedashop_articles_template_xlsx'),
    path('articles/export.xlsx', views.articles_export_xlsx, name='pedashop_articles_export_xlsx'),

    path('magasins/', views.magasin_list, name='pedashop_magasin_list'),
    path('magasins/nouveau/', views.magasin_form, name='pedashop_magasin_create'),
    path('magasins/<int:pk>/modifier/', views.magasin_form, name='pedashop_magasin_edit'),
    path('emplacements/', views.emplacement_list, name='pedashop_emplacement_list'),
    path('emplacements/nouveau/', views.emplacement_form, name='pedashop_emplacement_create'),
    path('stock/', views.stock_list, name='pedashop_stock_list'),
    path('stock/export.xlsx', views.stock_export_xlsx, name='pedashop_stock_export_xlsx'),
    path('stock/modele.xlsx', views.articles_template_xlsx, name='pedashop_stock_template_xlsx'),
    path('mouvements/', views.movement_list, name='pedashop_movement_list'),

    path('bons/', views.bon_list, name='pedashop_bon_list'),
    path('bons/nouveau/', views.bon_create, name='pedashop_bon_create'),
    path('bons/<int:pk>/', views.bon_detail, name='pedashop_bon_detail'),
    path('bons/<int:pk>/preparer/', views.bon_prepare, name='pedashop_bon_prepare'),
    path('bons/<int:pk>/distribuer/', views.bon_distribute, name='pedashop_bon_distribute'),
    path('bons/<int:pk>/retour/', views.bon_return, name='pedashop_bon_return'),
    path('bons/<int:bon_id>/reclamation/', views.reclamation_create, name='pedashop_reclamation_create'),
    path('bons/<int:pk>/inventaire-sortie/', views.bon_reception_inventory, name='pedashop_bon_reception_inventory'),
    path('inventaire/', views.inventory_adjustment, name='pedashop_inventory_adjustment'),
    path('entree-stock/', views.stock_entry, name='pedashop_stock_entry'),
    path('utilisateurs/', views.user_list, name='pedashop_user_list'),
    path('utilisateurs/<int:pk>/', views.user_detail, name='pedashop_user_detail'),
    path('utilisateurs/<int:pk>/visibilite/', views.user_visibility_update, name='pedashop_user_visibility_update'),
    path('bons/<int:pk>/pdf/', views.export_bon_pdf, name='pedashop_bon_pdf'),

    path('projections/', views.projection_list, name='pedashop_projection_list'),
    path('projections/nouveau/', views.projection_create, name='pedashop_projection_create'),
    path('reservations/', views.reservation_list, name='pedashop_reservation_list'),

    path('reclamations/', views.reclamation_list, name='pedashop_reclamation_list'),
    path('alertes/', views.alert_list, name='pedashop_alert_list'),
    path('consultations/', views.consultation_list, name='pedashop_consultation_list'),
    path('consultations/<int:pk>/modifier/', views.consultation_edit, name='pedashop_consultation_edit'),
    path('consultations/<int:pk>/pdf/', views.consultation_pdf, name='pedashop_consultation_pdf'),

    path('transfert/', views.transfer_create, name='pedashop_transfer_create'),
    path('import-excel/', views.import_excel, name='pedashop_import_excel'),
    path('exports/stock.pdf', views.export_stock_pdf, name='pedashop_stock_pdf'),
]
