from django.urls import path
from . import views

urlpatterns=[
 path('portal-login/',views.portal_login,name='pfmp_portal_login'),
 path('login/',views.login_view,name='pfmp_login'), path('logout/',views.logout_view,name='pfmp_logout'),
 path('sync-lp-core/',views.sync_lp_core_view,name='pfmp_sync_lp_core'),
 path('',views.dashboard,name='pfmp_dashboard'),
 path('entreprises/',views.company_list,name='pfmp_company_list'),
 path('entreprises/creer/',views.company_create,name='pfmp_company_create'),
 path('entreprises/<int:pk>/modifier/',views.company_update,name='pfmp_company_update'),
 path('entreprises/import/',views.import_companies,name='pfmp_company_import'),
 path('entreprises/<int:pk>/',views.company_detail,name='pfmp_company_detail'),
 path('entreprises/<int:company_pk>/contacts/creer/',views.contact_create,name='pfmp_contact_create'),
 path('entreprises/<int:company_pk>/contacts/<int:contact_pk>/modifier/',views.contact_update,name='pfmp_contact_update'),
 path('entreprises/<int:company_pk>/ajouter-recherche/',views.search_add_company,name='pfmp_search_add_company'),
 path('carte/',views.map_view,name='pfmp_map'),
 path('api/entreprises.geojson/',views.company_geojson,name='pfmp_company_geojson'),
 path('mes-recherches/',views.my_searches,name='pfmp_my_searches'),
 path('mes-recherches/pdf/',views.search_pdf,name='pfmp_search_pdf'),
 path('mes-recherches/<int:search_pk>/',views.search_detail,name='pfmp_search_detail'),
 path('mes-recherches/<int:search_pk>/actions/creer/',views.search_action_create,name='pfmp_search_action_create'),
 path('periodes/',views.period_list,name='pfmp_period_list'),
 path('periodes/creer/',views.period_create,name='pfmp_period_create'),
 path('periodes/<int:period_pk>/bilan/',views.period_summary,name='pfmp_period_summary'),
 path('affectations/',views.assignment_list,name='pfmp_assignment_list'),
 path('affectations/creer/',views.assignment_create,name='pfmp_assignment_create'),
 path('affectations/<int:assignment_pk>/demarches/creer/',views.step_create,name='pfmp_step_create'),
 path('annonces/',views.announcement_list,name='pfmp_announcement_list'),
 path('annonces/creer/',views.announcement_create,name='pfmp_announcement_create'),
 path('aide/',views.help_view,name='pfmp_help'), path('a-propos/',views.about_view,name='pfmp_about'),
 path('api/health/',views.api_health,name='pfmp_api_health'),
]
