from django.urls import path, include
from . import views
from . import views_v2

urlpatterns = [
    path('exports/configuration/', views.export_pdf_config, name='tp_export_config'),
    path('portal-login/', views.portal_login, name='tp_portal_login'),
    path('aide/', views.help_view, name='tp_help'),
    path('a-propos/', views.about_view, name='tp_about'),
    path('login/', views.login_view, name='tp_login'),
    path('logout/', views.logout_view, name='tp_logout'),
    path('sync-lp-core/', views.sync_lp_core_view, name='tp_sync_lp_core'),
    path('sync-system-manager/', views.sync_systems_view, name='tp_sync_system_manager'),
    path('', views_v2.dashboard, name='tp_dashboard'),
    path('tps/', views_v2.tp_list, name='tp_list'),
    path('tps/creer/', views_v2.tp_create, name='tp_create'),
    path('tps/export/pdf/', views.export_selection_pdf, name='tp_export_selection_pdf'),
    path('tps/<int:pk>/', views_v2.tp_detail, name='tp_detail'),
    path('tps/<int:pk>/modifier/', views_v2.tp_update, name='tp_update'),
    path('tps/<int:pk>/supprimer/', views_v2.tp_delete, name='tp_delete'),
    path('tps/<int:pk>/ajouter-a-mon-parcours/', views.request_tp_for_me, name='tp_request_for_me'),
    path('tps/<int:tp_pk>/documents/ajouter/', views_v2.document_add, name='tp_document_add'),
    path('tps/<int:tp_pk>/formations/ajouter/', views.tpformation_add, name='tp_formation_add'),
    path('tps/<int:tp_pk>/systemes/ajouter/', views.tpsysteme_add, name='tp_systeme_add'),
    path('tps/<int:tp_pk>/competences/ajouter/', views.tpcompetence_add, name='tp_competence_add'),
    path('tps/<int:tp_pk>/taches/ajouter/', views.tptache_add, name='tp_tache_add'),
    path('tps/<int:tp_pk>/savoirs/ajouter/', views.tpsavoir_add, name='tp_savoir_add'),
    path('tps/<int:tp_pk>/criteres/ajouter/', views.tpcritere_add, name='tp_critere_add'),
    path('tps/<int:tp_pk>/prerequis/ajouter/', views.tpprerequis_add, name='tp_prerequis_add'),
    path('tps/<int:tp_pk>/suivants/ajouter/', views.tpsuivant_add, name='tp_suivant_add'),

    path('tps/<int:pk>/dupliquer/', views_v2.tp_duplicate, name='tp_duplicate'),
    path('tps/<int:pk>/affecter-referentiel/', views_v2.tp_referentiel_affect, name='tpv2_referentiel_affect'),
    path('tps/<int:tp_pk>/v2/competences/ajouter/', views_v2.tp_competence_add, name='tpv2_competence_add'),
    path('tps/<int:tp_pk>/v2/criteres-reussite/ajouter/', views_v2.tp_success_criterion_add, name='tpv2_success_add'),
    path('tps/<int:tp_pk>/v2/evaluation-finale/ajouter/', views_v2.tp_final_criterion_add, name='tpv2_final_add'),
    path('tps/<int:tp_pk>/v2/ressources/groupes/ajouter/', views_v2.resource_group_add, name='tpv2_resource_group_add'),
    path('tps/v2/ressources/groupes/<int:group_pk>/items/ajouter/', views_v2.resource_item_add, name='tpv2_resource_item_add'),
    path('tps/<int:tp_pk>/v2/liens/blocs/ajouter/', views_v2.linked_block_add, name='tpv2_linked_block_add'),
    path('tps/v2/liens/blocs/<int:block_pk>/items/ajouter/', views_v2.linked_item_add, name='tpv2_linked_item_add'),
    path('api/v2/diplomes/<int:diplome_pk>/refs/', views_v2.api_diplome_refs, name='tpv2_api_diplome_refs'),
    path('api/v2/resources/search/', views_v2.api_resource_search, name='tpv2_api_resource_search'),
    path('evaluations/', include('evaluation_manager.urls')),
    path('parcours/', views.parcours_list, name='parcours_list'),
    path('parcours/affecter/', views_v2.parcours_assign, name='tpv2_parcours_assign'),
    path('parcours/<int:pk>/', views.parcours_detail, name='parcours_detail'),
    path('parcours/<int:pk>/export-docx/', views.parcours_export_docx, name='parcours_export_docx'),
    path('parcours/<int:parcours_pk>/traces/ajouter/', views.trace_add, name='trace_add'),
    path('parcours/<int:parcours_pk>/evaluation/ajouter/', views.evaluation_add, name='evaluation_add'),
    path('sequences/', views.sequence_list, name='sequence_list'),
    path('sequences/creer/', views.sequence_create, name='sequence_create'),
    path('sequences/<int:pk>/', views.sequence_detail, name='sequence_detail'),
    path('sequences/<int:pk>/affecter/', views.sequence_assign, name='sequence_assign'),
    path('sequences/<int:sequence_pk>/tps/ajouter/', views.sequence_add_tp, name='sequence_add_tp'),
    path('parametrage/', views.referentials, name='tp_referentials'),
    path('admin-sql/', views.sql_database_admin, name='sql_database_admin'),
    path('admin-sql/export.sql', views.sql_database_export, name='sql_database_export'),
    path('admin-sql/import/', views.sql_database_import, name='sql_database_import'),
    path('parametrage/zones/creer/', views.zone_create, name='tp_zone_create'),
    path('parametrage/themes-generaux/creer/', views.theme_general_create, name='tp_theme_general_create'),
    path('parametrage/themes-secondaires/creer/', views.theme_secondaire_create, name='tp_theme_secondaire_create'),
    path('parametrage/types-tp/creer/', views.type_tp_create, name='tp_type_create'),
    path('parametrage/systemes/creer/', views.systeme_ref_create, name='tp_systeme_ref_create'),
    path('parametrage/niveaux/creer/', views.niveau_create, name='tp_niveau_create'),
    path('parametrage/formations-niveaux/creer/', views.formation_niveau_create, name='tp_formation_niveau_create'),
    path('parametrage/referentiels/import-csv/', views.referentiel_import_csv, name='tp_referentiel_import_csv'),
    path('parametrage/contributions/creer/', views.contribution_permission_create, name='tp_contribution_create'),
    path('api/health/', views.api_health, name='tp_api_health'),
]
