# Generated manually for PFMP Manager V0.3.0
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Formation', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('core_formation_id',models.IntegerField(blank=True,null=True,unique=True)),('code',models.CharField(max_length=40,unique=True)),('nom',models.CharField(max_length=160)),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='PfmpUser', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('core_user_id',models.IntegerField(blank=True,null=True,unique=True)),('code',models.CharField(db_index=True,max_length=40)),('username',models.CharField(max_length=80,unique=True)),('first_name',models.CharField(blank=True,max_length=80)),('last_name',models.CharField(blank=True,max_length=80)),('email',models.EmailField(blank=True,max_length=254)),('formation_code',models.CharField(blank=True,max_length=40)),('formation_name',models.CharField(blank=True,max_length=160)),('class_name',models.CharField(blank=True,max_length=80)),('group_name',models.CharField(blank=True,max_length=80)),('role_principal',models.CharField(choices=[('eleve','Élève'),('utilisateur','Utilisateur'),('magasinier','Magasinier'),('professeur','Professeur'),('responsable','Responsable'),('admin','Administrateur')],default='utilisateur',max_length=30)),('rights',models.TextField(blank=True)),('active',models.BooleanField(default=True)),('school_year',models.CharField(blank=True,max_length=20)),('password',models.CharField(blank=True,max_length=160)),('synced_at',models.DateTimeField(blank=True,null=True))]),
        migrations.CreateModel(name='Company', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('activity',models.CharField(blank=True,max_length=220)),('address',models.CharField(blank=True,max_length=240)),('city',models.CharField(blank=True,max_length=120)),('postal_code',models.CharField(blank=True,max_length=20)),('latitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('longitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('phone',models.CharField(blank=True,max_length=40)),('email',models.EmailField(blank=True,max_length=254)),('website',models.URLField(blank=True)),('transport_access',models.CharField(blank=True,max_length=220)),('student_visible_notes',models.TextField(blank=True)),('internal_comment',models.TextField(blank=True)),('safety_notes',models.TextField(blank=True)),('global_rating',models.PositiveSmallIntegerField(default=0)),('status',models.CharField(choices=[('active','Active'),('a_verifier','À vérifier'),('provisoire','Provisoire élève'),('inactive','Inactive')],default='active',max_length=30)),('updated_at',models.DateTimeField(auto_now=True)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='companies_created',to='pfmp_manager.pfmpuser')),('formations',models.ManyToManyField(blank=True,to='pfmp_manager.formation'))]),
        migrations.CreateModel(name='CompanyContact', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('full_name',models.CharField(max_length=160)),('role',models.CharField(blank=True,max_length=120)),('service',models.CharField(blank=True,max_length=120)),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=40)),('contact_type',models.CharField(choices=[('pfmp','PFMP'),('alternance','Alternance'),('emploi','Emploi'),('convention','Convention'),('administratif','Administratif'),('technique','Technique'),('rh','RH général')],default='pfmp',max_length=30)),('visibility',models.CharField(choices=[('students','Visible élèves autorisés'),('professors','Professeurs seulement'),('admins','Administrateurs seulement')],default='professors',max_length=30)),('active',models.BooleanField(default=True)),('note',models.TextField(blank=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='contacts',to='pfmp_manager.company')),('formations',models.ManyToManyField(blank=True,to='pfmp_manager.formation'))]),
        migrations.CreateModel(name='PfmpPeriod', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('start_date',models.DateField()),('end_date',models.DateField()),('search_deadline',models.DateField(blank=True,null=True)),('class_names',models.CharField(blank=True,help_text='Classes concernées, séparées par ;',max_length=255)),('status',models.CharField(choices=[('preparation','Préparation'),('open','Saisie ouverte'),('closed','Saisie fermée'),('archived','Archivée')],default='preparation',max_length=30)),('notes',models.TextField(blank=True)),('formations',models.ManyToManyField(blank=True,to='pfmp_manager.formation')),('referent',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='pfmp_periods',to='pfmp_manager.pfmpuser'))]),
        migrations.CreateModel(name='StudentAssignment', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('searching','Recherche'),('proposed','Entreprise proposée'),('validated','Validée'),('convention','Convention en cours'),('in_progress','En PFMP'),('completed','Terminée'),('blocked','Bloquée')],default='searching',max_length=30)),('student_comment',models.TextField(blank=True)),('teacher_comment',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assignments',to='pfmp_manager.company')),('period',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assignments',to='pfmp_manager.pfmpperiod')),('student',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='pfmp_assignments',to='pfmp_manager.pfmpuser')),('teacher',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='pfmp_followed_students',to='pfmp_manager.pfmpuser')),('tutor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='tutored_assignments',to='pfmp_manager.companycontact'))], options={'unique_together':{('student','period')}}),
        migrations.CreateModel(name='StudentStep', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('step_type',models.CharField(choices=[('contact','Contact entreprise'),('cv','CV'),('letter','Lettre'),('phone','Appel'),('mail','Mail'),('visit','Visite'),('document','Document'),('other','Autre')],default='contact',max_length=30)),('date',models.DateField(default=django.utils.timezone.localdate)),('title',models.CharField(max_length=180)),('comment',models.TextField(blank=True)),('assignment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='steps',to='pfmp_manager.studentassignment')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='pfmp_manager.pfmpuser'))]),
        migrations.CreateModel(name='CompanyAnnouncement', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('announcement_type',models.CharField(choices=[('pfmp','Offre PFMP'),('alternance','Alternance'),('emploi','Emploi'),('job','Job étudiant'),('visite','Visite entreprise'),('evenement','Événement recrutement')],default='pfmp',max_length=30)),('places',models.PositiveIntegerField(default=1)),('period_text',models.CharField(blank=True,max_length=160)),('missions',models.TextField(blank=True)),('expected_profile',models.TextField(blank=True)),('mobility',models.CharField(blank=True,max_length=160)),('requires_driving_license',models.BooleanField(default=False)),('requires_vehicle',models.BooleanField(default=False)),('public_transport_ok',models.BooleanField(default=True)),('deadline',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('draft','Brouillon'),('pending','En attente de validation'),('published','Publiée'),('expired','Expirée'),('archived','Archivée')],default='draft',max_length=30)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='announcements',to='pfmp_manager.company')),('formations',models.ManyToManyField(blank=True,to='pfmp_manager.formation'))]),
    ]
