# Generated by patch_pfmp_relais_proximite_contacts.py
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfmp_manager', '0002_rc16_pfmp_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='student_extra_info',
            field=models.TextField(blank=True, help_text='Information affichée aux élèves pour ce contact, sans donnée personnelle sensible.', verbose_name='Info complémentaire visible élèves'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='local_relay_possible',
            field=models.BooleanField(default=False, help_text='Si activé, le contact n’est pas affiché comme contact élève classique mais son point GPS peut servir de relais de proximité.', verbose_name='Relais de proximité possible'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='relay_student_info',
            field=models.TextField(blank=True, help_text='Texte affiché aux élèves avec la mention relais de proximité possible.', verbose_name='Info relais visible élèves'),
        ),
    ]
