# Generated for LP Gestion Atelier Suite v2.9.3
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('tp_manager', '0008_tpv2_bareme_on_criteria_only'),
    ]
    operations = [
        migrations.CreateModel(
            name='SeqColoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('formelle', 'Formelle'), ('etablissement', 'Établissement'), ('locale', 'Locale')], default='formelle', max_length=30)),
                ('couleur', models.CharField(default='#2563eb', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={'verbose_name': 'coloration de séquence', 'verbose_name_plural': 'colorations de séquence', 'ordering': ['nom']},
        ),
        migrations.CreateModel(
            name='SeqWeeklySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('half_day', models.CharField(choices=[('AM', 'Matin'), ('PM', 'Après-midi')], max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={'verbose_name': 'créneau hebdomadaire', 'verbose_name_plural': 'créneaux hebdomadaires', 'ordering': ['day', 'half_day'], 'unique_together': {('day', 'half_day')}},
        ),
        migrations.CreateModel(
            name='SeqZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('capacite_max', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('systemes', models.ManyToManyField(blank=True, related_name='seq_zones', to='tp_manager.systemepedagogiqueref')),
            ],
            options={'verbose_name': 'zone Sequence Manager', 'verbose_name_plural': 'zones Sequence Manager', 'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='SeqRotationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('professeurs', models.ManyToManyField(blank=True, related_name='seq_rotation_blocks', to='tp_manager.tpuser')),
                ('slots', models.ManyToManyField(blank=True, related_name='rotation_blocks', to='sequence_manager.seqweeklyslot')),
                ('zones', models.ManyToManyField(blank=True, related_name='rotation_blocks', to='sequence_manager.seqzone')),
            ],
            options={'verbose_name': 'bloc de rotation', 'verbose_name_plural': 'blocs de rotation', 'ordering': ['nom']},
        ),
        migrations.CreateModel(
            name='SeqRotationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation_code', models.CharField(max_length=40)),
                ('classe', models.CharField(blank=True, max_length=120)),
                ('niveau', models.CharField(blank=True, max_length=80)),
                ('effectif_prevu', models.PositiveIntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='sequence_manager.seqrotationblock')),
            ],
            options={'verbose_name': 'formation dans bloc de rotation', 'verbose_name_plural': 'formations dans blocs de rotation', 'ordering': ['block__nom', 'formation_code', 'classe']},
        ),
        migrations.CreateModel(
            name='SeqSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=220)),
                ('code', models.CharField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('axe_principal', models.CharField(blank=True, max_length=180)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('nb_semaines', models.PositiveIntegerField(default=3)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('locked', 'Verrouillée'), ('done', 'Terminée'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('auto_inscription_libre', models.BooleanField(default=False, help_text='Premier arrivé, premier servi pour les parcours libres.')),
                ('validation_prof_requise', models.BooleanField(default=True)),
                ('notes_tp_activees', models.BooleanField(default=False)),
                ('sequence_modele', models.BooleanField(default=False)),
                ('coloration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='sequence_manager.seqcoloration')),
                ('professeurs', models.ManyToManyField(blank=True, related_name='seq_sequences_prof', to='tp_manager.tpuser')),
                ('rotation_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='sequence_manager.seqrotationblock')),
                ('slots', models.ManyToManyField(blank=True, related_name='seq_sequences', to='sequence_manager.seqweeklyslot')),
                ('zone_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='sequence_manager.seqzone')),
                ('zones', models.ManyToManyField(blank=True, related_name='seq_sequences', to='sequence_manager.seqzone')),
            ],
            options={'verbose_name': 'séquence', 'verbose_name_plural': 'séquences', 'ordering': ['-date_debut', 'titre']},
        ),
        migrations.CreateModel(
            name='SeqSequenceFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation_code', models.CharField(max_length=40)),
                ('classe', models.CharField(blank=True, max_length=120)),
                ('niveau', models.CharField(blank=True, max_length=80)),
                ('effectif', models.PositiveIntegerField(default=0)),
                ('diplome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seq_formations', to='tp_manager.bacdiplome')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='sequence_manager.seqsequence')),
            ],
            options={'verbose_name': 'formation concernée par séquence', 'verbose_name_plural': 'formations concernées par séquence', 'ordering': ['sequence__date_debut', 'formation_code', 'classe'], 'unique_together': {('sequence', 'formation_code', 'classe')}},
        ),
        migrations.CreateModel(
            name='SeqPresenceWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('formation_code', models.CharField(max_length=40)),
                ('classe', models.CharField(blank=True, max_length=120)),
                ('type_presence', models.CharField(choices=[('fixed', 'Groupe fixe'), ('wave', 'Vague courte'), ('free', 'Parcours libre'), ('pfmp', 'PFMP')], default='fixed', max_length=20)),
                ('semaine_debut', models.PositiveIntegerField(default=1)),
                ('duree_semaines', models.PositiveIntegerField(default=1)),
                ('eleves', models.ManyToManyField(blank=True, related_name='seq_waves', to='tp_manager.tpuser')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='sequence_manager.seqsequence')),
            ],
            options={'verbose_name': 'vague de présence', 'verbose_name_plural': 'vagues de présence', 'ordering': ['sequence', 'semaine_debut', 'formation_code', 'nom']},
        ),
        migrations.CreateModel(
            name='SeqStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('type_groupe', models.CharField(choices=[('solo', 'Élève seul'), ('binome', 'Binôme'), ('trinome', 'Trinôme'), ('group', 'Groupe'), ('mixed', 'Groupe mixte'), ('free', 'Parcours libre')], default='binome', max_length=20)),
                ('formation_dominante', models.CharField(blank=True, max_length=40)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('parcours_libre', models.BooleanField(default=False)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='sequence_manager.seqsequence')),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='sequence_manager.seqpresencewave')),
            ],
            options={'verbose_name': 'groupe élève de séquence', 'verbose_name_plural': 'groupes élèves de séquence', 'ordering': ['sequence', 'ordre', 'nom']},
        ),
        migrations.CreateModel(
            name='SeqStudentGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='membre', max_length=40)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_group_memberships', to='tp_manager.tpuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sequence_manager.seqstudentgroup')),
            ],
            options={'verbose_name': 'membre de groupe séquence', 'verbose_name_plural': 'membres de groupes séquence', 'ordering': ['group__ordre', 'ordre', 'eleve__last_name'], 'unique_together': {('group', 'eleve')}},
        ),
        migrations.CreateModel(
            name='SeqSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('semaine', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('titre', models.CharField(blank=True, max_length=160)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sequence_manager.seqsequence')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='sequence_manager.seqweeklyslot')),
            ],
            options={'verbose_name': 'séance', 'verbose_name_plural': 'séances', 'ordering': ['sequence', 'date', 'slot__day', 'slot__half_day'], 'unique_together': {('sequence', 'numero')}},
        ),
        migrations.CreateModel(
            name='SeqAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('impose', 'Parcours imposé'), ('libre', 'Parcours libre'), ('remediation', 'Remédiation'), ('pfmp', 'PFMP'), ('evaluation', 'Évaluation')], default='impose', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Prévu'), ('requested', 'Demandé'), ('validated', 'Validé'), ('done', 'Réalisé'), ('cancelled', 'Annulé'), ('postponed', 'Reporté')], default='planned', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('tp_note', models.BooleanField(default=False)),
                ('capacite_max', models.PositiveIntegerField(default=2)),
                ('eleve_individuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seq_assignments', to='tp_manager.tpuser')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='sequence_manager.seqstudentgroup')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seq_assignments_prof', to='tp_manager.tpuser')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sequence_manager.seqsession')),
                ('systeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seq_assignments', to='tp_manager.systemepedagogiqueref')),
                ('tp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seq_assignments', to='tp_manager.tpv2')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='sequence_manager.seqzone')),
            ],
            options={'verbose_name': 'affectation de séance', 'verbose_name_plural': 'affectations de séance', 'ordering': ['session__date', 'session__numero', 'group__ordre', 'id']},
        ),
        migrations.CreateModel(
            name='SeqSystemBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pre_reserved', 'Pré-réservé'), ('reserved', 'Réservé'), ('used', 'Utilisé'), ('cancelled', 'Annulé'), ('conflict', 'Conflit')], default='reserved', max_length=20)),
                ('source', models.CharField(choices=[('sequence', 'Séquence'), ('system_manager', 'System Manager'), ('manual', 'Manuel')], default='sequence', max_length=20)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_bookings', to='sequence_manager.seqassignment')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_bookings', to='sequence_manager.seqsequence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_bookings', to='sequence_manager.seqsession')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_bookings', to='tp_manager.systemepedagogiqueref')),
            ],
            options={'verbose_name': 'réservation système séquence', 'verbose_name_plural': 'réservations systèmes séquence', 'ordering': ['session__date', 'systeme__code']},
        ),
        migrations.CreateModel(
            name='SeqFreeChoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon élève'), ('submitted', 'Soumise'), ('validated', 'Validée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('commentaire_eleve', models.TextField(blank=True)),
                ('commentaire_prof', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_free_requests', to='tp_manager.tpuser')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_requests', to='sequence_manager.seqsequence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_requests', to='sequence_manager.seqsession')),
                ('systeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seq_free_requests', to='tp_manager.systemepedagogiqueref')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_free_requests', to='tp_manager.tpv2')),
            ],
            options={'verbose_name': 'demande parcours libre', 'verbose_name_plural': 'demandes parcours libre', 'ordering': ['-created_at'], 'unique_together': {('session', 'eleve')}},
        ),
    ]
